services:

    j2Exchange.menu_renderer:
        class: J2\Bundle\ExchangeBundle\Menu\Renderer\CustomRenderer
        arguments: [@knp_menu.matcher] # set your own dependencies here
        tags:
            # The alias is what is used to retrieve the menu
            - { name: knp_menu.renderer, alias: custom }

    twig.extension.j2exchange.text_extension:
            class: J2\Bundle\ExchangeBundle\Twig\Text
            tags:
                - { name: twig.extension }