<?php

namespace J2\Bundle\ExchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriesRepository extends EntityRepository
{   
    /**
     * Fetch all active categories 
     * @return array 
     */
    public static function getActiveCategories(){}
    
    /**
     * Fetch all inactive categories 
     * @return array  
     */
    public static function getInactiveCategories(){}
}