<?php

namespace J2\Bundle\ExchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use J2\Bundle\ExchangeBundle\Entity\Offers;

/**
 * OfferRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OfferRepository extends EntityRepository
{
    
    /**
     * Fetch all active offers for company
     * @param Company $company
     * @return array 
     */
    public function getActiveOffersByCompany(Company $company){

        $qb = $this->createQueryBuilder('o');
        $qb->where('o.company = :company')
            ->andWhere('o.active = :active')
            ->setParameter('company', $company)
            ->setParameter('active', true);

        return $qb->getQuery()->execute();
    }
}