<?php

namespace J2\Bundle\ExchangeBundle\Entity;

use Doctrine\ORM\EntityRepository;
use J2\Bundle\ExchangeBundle\Entity\Products;

/**
 * ProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    
    /**
     * Fetch an product by id from within a company exchange
     * @param int $productID 
     * @return Product
     */
    public function findProduct($productID){
        return $this->find($productID);
    }

    /**
     *
     * @param User $user
     * @return type 
     */
    public function findByUser(User $user)
    {
        $qb = $this->createQueryBuilder('p');
        $qb->where('p.company = :company')
           ->andWhere('p.exchange = :exchange')
           ->setParameter('company', $user->getCompany())
           ->setParameter('exchange', $user->getCurrentExchange());

        return $qb->getQuery()->execute();
    }
}