J2\Bundle\ExchangeBundle\Entity\Company:
    exclusion_policy: ALL
    exclude: false
    access_type: public_method # defaults to property
    properties:
      id:
        expose: true
        read_only: true
        access_type: private_method
      name:
        expose: true
      createdAt:
        expose: true
      active:
        expose: true
      deals:
        expose: true