J2\Bundle\ExchangeBundle\Entity\Offer:
    exclusion_policy: ALL
    exclude: false
    access_type: public_method # defaults to property
    properties:
      id:
        expose: true
        read_only: true
        access_type: private_method
      name:
        expose: true
      listPrice:
        expose: true
      whisperPrice:
        expose: true
      createdAt:
        expose: true
      updatedAt:
        expose: true
      active:
        expose: true
        serialized_name: isActive
      available:
        expose: true
      active:
        expose: true
      product:
        expose: true
      matches:
        expose: true
