J2\Bundle\ExchangeBundle\Entity\Deal:
    exclusion_policy: ALL
    exclude: false
    access_type: public_method # defaults to property
    properties:
      id:
        expose: true
        read_only: true
        access_type: private_method
      state:
        expose: true
      slug:
        expose: true
      offers:
        expose: true
      deals:
        expose: true
      revenueTotal:
        expose: true
      orderTotal:
        expose: true